ignores:
  [
    "@next/*",
    "@semantic-release/*",
    "@typescript-eslint/*",
    "autoprefixer",
    "eslint-*",
    "commitizen",
    "postcss",
    "git-cz",
    "stylelint-*",
    "typescript",
  ]
ignore-path: .gitignore
skip-missing: true
