ignores:
  [
    "@shunkakinoki/*",
    "@storybook/*",
    "autoprefixer",
    "npm-package-json-lint-config-shunkakinoki",
    "postcss",
    "storybook-builder-vite",
  ]
ignore-path: .gitignore
skip-missing: true
