pull_request_rules:
  - name: Renovate
    conditions:
      - author=renovate[bot]
      - check-success=Vercel – shunkakinoki
      - check-success=Vercel – storybook
      - check-success=check
    actions:
      merge:
        method: merge
