name: Serverless
on:
  push:
    branches:
      - main
jobs:
  serverless:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    strategy:
      fail-fast: false
      matrix:
        app: [shunkakinoki.com, og.shunkakinoki.com]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: dopplerhq/cli-action@v1
      - run: |
          doppler setup --no-interactive
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run env:pull
      - run: |
          bash ./script.sh ${{ matrix.app }}
      - run: |
          mv sls.${{ matrix.app }}.yml serverless.yml
      - if: ${{ matrix.app }} == shunkakinoki.com
        run: |
          yarn run prisma generate
      - run: |
          yarn run serverless
        env:
          AWS_ACL_ARN: ${{ secrets.AWS_ACL_ARN }}
